language: node_js
env:
  - LINUX_CXX=g++-4.8
os:
  - linux
  - osx
node_js:
  - "node"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  - echo Building for Node $TRAVIS_NODE_VERSION
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=$LINUX_CXX; $CXX --version; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then c++ --version; fi;
install: true
before_script:
  - npm install
script:
  - npm run build:ts
  - npm run build
  - npm test
after_success:
  - echo "Publishing"; npm install node-pre-gyp-github@1.4.3; ./node_modules/.bin/node-pre-gyp configure; ./node_modules/.bin/node-pre-gyp build; ./node_modules/.bin/node-pre-gyp package; ./node_modules/.bin/node-pre-gyp-github publish;
