language: node_js
env:
  - LINUX_CXX=g++-4.8
dist: trusty
os:
  - linux
  - osx
node_js:
  - "14"
  - "12"
  - "10"
  - "8"
before_install:
  - echo Building for Node $TRAVIS_NODE_VERSION
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=$LINUX_CXX; $CXX --version; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then c++ --version; fi;
install: true
before_script:
  - npm install
script:
  - npm run build:ts
  - npm run build
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build --build-arg VERSION=$TRAVIS_NODE_VERSION -t tmp/alpine-native-metrics .; fi;
after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker run -e NODE_PRE_GYP_GITHUB_TOKEN tmp/alpine-native-metrics; fi;
    echo "Publishing"; npm install node-pre-gyp-github@1.4.3; ./node_modules/.bin/node-pre-gyp configure; ./node_modules/.bin/node-pre-gyp build; ./node_modules/.bin/node-pre-gyp package; ./node_modules/.bin/node-pre-gyp-github publish;
  else
    echo "Not publishing"
  fi
